// 1.
export const GET_ALL_POSTS = "GET_ALL_POSTS";
export const GET_ALL_POSTS_SUCCESS = "GET_ALL_POSTS_SUCCESS";
export const GET_ALL_POSTS_FAILURE = "GET_ALL_POSTS_FAILURE";

// 2.
export const SHOW_MODAL = "SHOW_MODAL";
export const HIDE_MODAL = "HIDE_MODAL";

// 3.
export const CREATE_POST = "CREATE_POST";
export const CREATE_POST_SUCCESS = "CREATE_POST_SUCCESS";
export const CREATE_POST_FAILURE = "CREATE_POST_FAILURE";

// 4.
export const UPDATE_LIKE_COUNT_POST = "UPDATE_LIKE_COUNT_POST";
export const UPDATE_LIKE_COUNT_POST_SUCCESS = "UPDATE_LIKE_COUNT_POST_SUCCESS";
export const UPDATE_LIKE_COUNT_POST_FAILURE = "UPDATE_LIKE_COUNT_POST_FAILURE";